<?php

namespace StarkBank;
use StarkBank\Utils\Resource;
use StarkBank\Utils\Checks;
use StarkBank\Utils\Rest;
use StarkBank\Utils\API;
use StarkBank\Boleto;


class BoletoLog extends Resource
{
    /**
    # BoletoLog object

    Every time a Boleto entity is updated, a corresponding BoletoLog
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the Boleto.

    ## Attributes:
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - boleto [Boleto]: Boleto entity to which the log refers to.
        - errors [list of strings]: list of errors linked to this Boleto event
        - type [string]: type of the Boleto event which triggered the log creation. ex: "registered" or "paid"
        - created [datetime.datetime]: creation datetime for the boleto. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
     */
    function __construct(array $params)
    {
        parent::__construct($params["id"]);
        unset($params["id"]);
        $this->created = Checks::checkDateTime($params["created"]);
        unset($params["created"]);
        $this->type = $params["type"];
        unset($params["type"]);
        $this->errors = $params["errors"];
        unset($params["errors"]);
        $this->boleto = $params["boleto"];
        unset($params["boleto"]);

        Checks::checkParams($params);
    }

    /**
    Retrieve a specific BoletoLog

    Receive a single BoletoLog object previously created by the Stark Bank API by passing its id

    Parameters (required):
        id [string]: object unique id. ex: "5656565656565656"
    Parameters (optional):
        user [Project object]: Project object. Not necessary if starkbank.user was set before function call
    Return:
        BoletoLog object with updated attributes
     */
    public function get($user, $id)
    {
        return Rest::getId($user, BoletoLog::resource(), $id);
    }

    /**
    Retrieve BoletoLogs

    Receive a generator of BoletoLog objects previously created in the Stark Bank API

    Parameters (optional):
        limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
        boleto_ids [list of strings, default None]: list of Boleto ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        types [list of strings, default None]: filter for log event types. ex: "paid" or "registered"
        after [datetime.date, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
        before [datetime.date, default None] date filter for objects only before specified date. ex: datetime.date(2020, 3, 10)
        user [Project object, default None]: Project object. Not necessary if starkbank.user was set before function call
    Return:
        list of BoletoLog objects with updated attributes
     */
    public function query($user, $options = [])
    {
        $options["after"] = Checks::checkDateTime($options["after"]);
        $options["before"] = Checks::checkDateTime($options["before"]);
        return Rest::getList($user, BoletoLog::resource(), $options);
    }

    private function resource()
    {
        $boletoLog = function ($array) {
            $boleto = function ($array) {
                return new Boleto($array);
            };
            $array["boleto"] = API::fromApiJson($boleto, $array["boleto"]);
            return new BoletoLog($array);
        };
        return [
            "name" => "BoletoLog",
            "maker" => $boletoLog,
        ];
    }
}
