<?php

namespace StarkBank\InvoicePullRequest;
use StarkCore\Utils\API;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkBank\Utils\Rest;
use StarkBank\InvoicePullRequest;


class Log extends Resource
{

    public $created;
    public $type;
    public $errors;
    public $request;
    public $reason;
    public $description;

    /**
    # InvoicePullRequest\Log object

    Every time an InvoicePullRequest entity is updated, a corresponding InvoicePullRequest\Log is generated for the entity. This log is never generated by the user, but it can be retrieved to check additional information on the InvoicePullRequest.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - request [InvoicePullRequest]: InvoicePullRequest entity to which the log refers to.
        - errors [array of strings]: array of errors linked to this InvoicePullRequest event
        - type [string]: type of the InvoicePullRequest event which triggered the log creation.
        - reason [string]: reason for the log's type, when applicable.
        - description [string]: description for the log's type, when applicable.
        - created [DateTime]: creation datetime for the log.
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this->type = Checks::checkParam($params, "type");
        $this->errors = Checks::checkParam($params, "errors");
        $this->request = Checks::checkParam($params, "request");
        $this->reason = Checks::checkParam($params, "reason");
        $this->description = Checks::checkParam($params, "description");


        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific Log

    Receive a single Log object previously created by the Stark Bank API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve Logs

    Receive an enumerator of Log objects previously created in the Stark Bank API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null.
        - after [DateTime or string, default null]: date filter for objects created only after specified date.
        - before [DateTime or string, default null]: date filter for objects created only before specified date.
        - types [array of strings, default null]: filter for log event types.
        - requestIds [array of strings, default null]: array of InvoicePullRequest ids to filter logs.
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - enumerator of Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged Logs

    Receive a list of up to 100 Log objects previously created in the Stark Bank API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100.
        - after, before, types, requestIds: same filters as query
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was set before function call

    ## Return:
        - list of Log objects with updated attributes
        - cursor to retrieve the next page of Log objects
     */
    public static function page($options = [], $user = null)
    {
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $invoicePullRequestLog = function ($array) {
            $request = function ($array) {
                return new InvoicePullRequest($array);
            };
            $array["request"] = API::fromApiJson($request, $array["request"]);
            return new Log($array);
        };
        return [
            "name" => "InvoicePullRequestLog",
            "maker" => $invoicePullRequestLog,
        ];
    }
}
