<?php

namespace StarkBank\BoletoHolmes;
use StarkBank\Utils\Resource;
use StarkBank\Utils\Checks;
use StarkBank\Utils\Rest;
use StarkBank\Utils\API;
use StarkBank\BoletoHolmes;

class Log extends Resource
{
    /**
    # BoletoHolmes\Log object

    Every time a BoletoHolmes entity is modified, a corresponding boletoholmes.Log
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the BoletoHolmes.

    ## Attributes:
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - holmes [BoletoHolmes]: BoletoHolmes entity to which the log refers to.
        - type [string]: type of the BoletoHolmes event which triggered the log creation. ex: "solving" or "solved"
        - created [DateTime, default null]: creation datetime for the holmes. ex: DateTime('2020-01-01T15:03:01.012345Z')
        - updated [DateTime, default null]: latest update datetime for the holmes. ex: DateTime('2020-01-01T15:03:01.012345Z')
     */
    function __construct(array $params)
    {
        parent::__construct($params);
        
        $this->holmes = Checks::checkParam($params, "holmes");
        $this->type = Checks::checkParam($params, "type");
        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific BoletoHolmes\Log

    Receive a single boletoHolmes.Log object previously created by the Stark Bank API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Project object]: Project object. Not necessary if StarkBank\User.setDefaut() was set before function call

    ## Return:
        - BoletoHolmes\Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve BoletoHolmes\Log's

    Receive a generator of BoletoHolmes\Log objects previously created in the Stark Bank API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [DateTime or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [DateTime or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter retrieved objects by event type. ex: ["solving", "solved"]
        - holmesIds [array of strings, default null]: array of BoletoHolmes ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Project object, default null]: Project object. Not necessary if starkbank.user was set before function call

    ## Return:
        - array of BoletoHolmes\Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = Checks::checkDateTime(Checks::checkParam($options, "after"));
        $options["before"] = Checks::checkDateTime(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $sherlockLog = function ($array) {
            $holmes = function ($array) {
                return new BoletoHolmes($array);
            };
            $array["holmes"] = API::fromApiJson($holmes, $array["holmes"]);
            return new Log($array);
        };
        return [
            "name" => "BoletoHolmesLog",
            "maker" => $sherlockLog,
        ];
    }
}