<?php

namespace StarkBank\BoletoHolmes;
use StarkCore\Utils\API;
use StarkBank\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkBank\BoletoHolmes;


class Log extends Resource
{

    public $holmes;
    public $type;
    public $created;
    public $updated;

    /**
    # BoletoHolmes\Log object

    Every time a BoletoHolmes entity is modified, a corresponding boletoholmes.Log
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the BoletoHolmes.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - holmes [BoletoHolmes]: BoletoHolmes entity to which the log refers to.
        - type [string]: type of the BoletoHolmes event which triggered the log creation. ex: "solving" or "solved"
        - created [DateTime]: creation datetime for the holmes. ex: DateTime('2020-01-01T15:03:01.012345Z')
        - updated [DateTime]: latest update datetime for the holmes. ex: DateTime('2020-01-01T15:03:01.012345Z')
     */
    function __construct(array $params)
    {
        parent::__construct($params);
        
        $this->holmes = Checks::checkParam($params, "holmes");
        $this->type = Checks::checkParam($params, "type");
        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this->updated = Checks::checkDateTime(Checks::checkParam($params, "updated"));

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific BoletoHolmes\Log

    Receive a single boletoHolmes.Log object previously created by the Stark Bank API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - BoletoHolmes\Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve BoletoHolmes\Log's

    Receive a generator of BoletoHolmes\Log objects previously created in the Stark Bank API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [DateTime or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [DateTime or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter retrieved objects by event type. ex: ["solving", "solved"]
        - holmesIds [array of strings, default null]: array of BoletoHolmes ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - array of BoletoHolmes\Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged BoletoHolmes\Logs

    Receive a list of up to 100 BoletoHolmes\Log objects previously created in the Stark Bank API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - after [DateTime or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [DateTime or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter retrieved objects by event type. ex: ["solving", "solved"]
        - holmesIds [array of strings, default null]: array of BoletoHolmes ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call
    
    ## Return:
        - list of BoletoHolmes\Log objects with updated attributes
        - cursor to retrieve the next page of BoletoHolmes\Log objects
     */
    public static function page($options = [], $user = null)
    {
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $sherlockLog = function ($array) {
            $holmes = function ($array) {
                return new BoletoHolmes($array);
            };
            $array["holmes"] = API::fromApiJson($holmes, $array["holmes"]);
            return new Log($array);
        };
        return [
            "name" => "BoletoHolmesLog",
            "maker" => $sherlockLog,
        ];
    }
}