<?php

namespace StarkBank\MerchantCard;
use StarkCore\Utils\API;
use StarkBank\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkBank\MerchantCard;


class Log extends Resource
{

    public $created;
    public $type;
    public $errors;
    public $card;

    /**
    # MerchantCard\Log object

    Every time a MerchantCard entity is updated, a corresponding MerchantCard\Log is generated for the entity. This log is never generated by the user, but it can be retrieved to check additional information on the MerchantCard.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created.
        - card [MerchantCard]: MerchantCard entity to which the log refers to.
        - errors [array of strings]: array of errors linked to this MerchantCard event.
        - type [string]: type of the MerchantCard event which triggered the log creation.
        - created [DateTime]: creation datetime for the log.
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this->type = Checks::checkParam($params, "type");
        $this->errors = Checks::checkParam($params, "errors");
        $this->card = Checks::checkParam($params, "card");

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific Log

    Receive a single Log object previously created by the Stark Bank API by passing its id

    ## Parameters (required):
        - id [string]: object unique id.

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve Logs

    Receive an enumerator of Log objects previously created in the Stark Bank API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null.
        - after, before [DateTime or string, default null]: date filters.
        - cardIds [array of strings, default null]: array of MerchantCard ids to filter logs.
        - types [array of strings, default null]: filter for log event types.
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - enumerator of Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged Logs

    Receive a list of up to 100 Log objects previously created in the Stark Bank API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100.
        - (same filters as query: after, before, cardIds, types)
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was set before function call

    ## Return:
        - list of Log objects with updated attributes
        - cursor to retrieve the next page of Log objects
     */
    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $cardLog = function ($array) {
            $card = function ($array) {
                return new MerchantCard($array);
            };
            $array["card"] = API::fromApiJson($card, $array["card"]);
            return new Log($array);
        };
        return [
            "name" => "MerchantCardLog",
            "maker" => $cardLog,
        ];
    }
}
