<?php

namespace StarkBank\InvoicePullSubscription;
use StarkCore\Utils\API;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkBank\Utils\Rest;
use StarkBank\InvoicePullSubscription;


class Log extends Resource
{

    public $created;
    public $type;
    public $errors;
    public $subscription;
    public $reason;
    public $description;

    /**
    # InvoicePullSubscription\Log object

    Every time an InvoicePullSubscription entity is updated, a corresponding InvoicePullSubscription\Log is generated for the entity. This log is never generated by the user, but it can be retrieved to check additional information on the InvoicePullSubscription.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created.
        - subscription [InvoicePullSubscription]: InvoicePullSubscription entity to which the log refers to.
        - errors [array of strings]: array of errors linked to this InvoicePullSubscription event
        - type [string]: type of the InvoicePullSubscription event which triggered the log creation.
        - reason [string]: reason for the log's type, when applicable.
        - description [string]: description for the log's type, when applicable.
        - created [DateTime]: creation datetime for the log.
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this->type = Checks::checkParam($params, "type");
        $this->errors = Checks::checkParam($params, "errors");
        $this->subscription = Checks::checkParam($params, "subscription");
        $this->reason = Checks::checkParam($params, "reason");
        $this->description = Checks::checkParam($params, "description");

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific Log

    Receive a single Log object previously created by the Stark Bank API by passing its id

    ## Parameters (required):
        - id [string]: object unique id.

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve Logs

    Receive an enumerator of Log objects previously created in the Stark Bank API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null.
        - after, before [DateTime or string, default null]: date filters.
        - types [array of strings, default null]: filter for log event types.
        - subscriptionIds [array of strings, default null]: array of InvoicePullSubscription ids to filter logs.
        - tags [array of strings, default null]: tags to filter retrieved objects.
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - enumerator of Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged Logs

    Receive a list of up to 100 Log objects previously created in the Stark Bank API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100.
        - (same filters as query: after, before, types, subscriptionIds, tags)
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was set before function call

    ## Return:
        - list of Log objects with updated attributes
        - cursor to retrieve the next page of Log objects
     */
    public static function page($options = [], $user = null)
    {
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $invoicePullSubscriptionLog = function ($array) {
            $subscription = function ($array) {
                return new InvoicePullSubscription($array);
            };
            $array["subscription"] = API::fromApiJson($subscription, $array["subscription"]);
            return new Log($array);
        };
        return [
            "name" => "InvoicePullSubscriptionLog",
            "maker" => $invoicePullSubscriptionLog,
        ];
    }
}
