<?php

namespace StarkBank\VerifiedAccount;
use StarkCore\Utils\API;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkBank\Utils\Rest;
use StarkBank\VerifiedAccount;


class Log extends Resource
{

    public $created;
    public $type;
    public $errors;
    public $account;

    /**
    # VerifiedAccount\Log object

    Every time a VerifiedAccount entity is modified, a corresponding VerifiedAccount\Log
    is generated for the entity. This log is never generated by the
    user.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - account [VerifiedAccount]: VerifiedAccount entity to which the log refers to.
        - errors [array of strings]: array of errors linked to this VerifiedAccount event.
        - type [string]: type of the VerifiedAccount event which triggered the log creation. ex: "created" or "processing"
        - created [DateTime]: creation datetime for the log.
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this->type = Checks::checkParam($params, "type");
        $this->errors = Checks::checkParam($params, "errors");
        $this->account = Checks::checkParam($params, "account");

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific Log

    Receive a single Log object previously created by the Stark Bank API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve Logs

    Receive an enumerator of Log objects previously created in the Stark Bank API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [DateTime or string, default null] date filter for objects created only after specified date. ex: "2020-03-10"
        - before [DateTime or string, default null] date filter for objects created only before specified date. ex: "2020-03-10"
        - types [array of strings, default null]: filter retrieved objects by types. ex: "created" or "processing"
        - accountIds [array of strings, default null]: array of VerifiedAccount ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was used before function call

    ## Return:
        - enumerator of Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged Logs

    Receive a list of up to 100 Log objects previously created in the Stark Bank API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - after [DateTime or string, default null] date filter for objects created only after specified date. ex: "2020-03-10"
        - before [DateTime or string, default null] date filter for objects created only before specified date. ex: "2020-03-10"
        - types [array of strings, default null]: filter retrieved objects by types. ex: "created" or "processing"
        - accountIds [array of strings, default null]: array of VerifiedAccount ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was set before function call

    ## Return:
        - list of Log objects with updated attributes
        - cursor to retrieve the next page of Log objects
     */
    public static function page($options = [], $user = null)
    {
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $verifiedAccountLog = function ($array) {
            $account = function ($array) {
                return new VerifiedAccount($array);
            };
            $array["account"] = API::fromApiJson($account, $array["account"]);
            return new Log($array);
        };
        return [
            "name" => "VerifiedAccountLog",
            "maker" => $verifiedAccountLog,
        ];
    }
}
